import {
  ArrowLeftRight,
  Calendar,
  CalendarCheck,
  CalendarDays,
  ChartColumn,
  ChartPie,
  CircleDollarSign,
  Coffee,
  Contact,
  HandCoins,
  HandHeart,
  Inbox,
  LayoutDashboard,
  Plug,
  Scale,
  Settings,
  Share2,
  SlidersHorizontal,
  Tags,
  Target,
  UserCog,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/suite-preview/modules";

/** Nombres de ícono (lib/suite-preview/modules) → componentes lucide. */
export const ICONS: Record<IconName, LucideIcon> = {
  CircleDollarSign,
  CalendarDays,
  UsersRound,
  ChartColumn,
  Settings,
  LayoutDashboard,
  Inbox,
  ArrowLeftRight,
  Wallet,
  Scale,
  HandCoins,
  HandHeart,
  Coffee,
  Target,
  Calendar,
  CalendarCheck,
  Share2,
  Contact,
  SlidersHorizontal,
  Tags,
  UserCog,
  Plug,
  PieChart: ChartPie,
};
